package io.helidon.examples.student;

import io.helidon.logging.common.LogConfig;
import io.helidon.service.registry.Service;
import io.helidon.service.registry.ServiceRegistryManager;
import io.helidon.webserver.WebServer;

/**
 * Main class for the Student Management Service using Helidon SE 4.x Declarative APIs.
 *
 * This application demonstrates:
 * 1. **Helidon REST Endpoints** - @RestServer.Endpoint with annotations
 * 2. **Helidon Data Repository** - JPA/Hibernate with automatic query generation
 * 3. **Dependency Injection** - Constructor injection via ServiceRegistry
 * 4. **Build-time Service Discovery** - ApplicationBinding generated at compile time
 * 5. **OpenTelemetry tracing** (auto-configured)
 *
 * Helidon Declarative Pattern (Official):
 * - @Service.GenerateBinding: Triggers ApplicationBinding code generation
 * - ServiceRegistryManager.start(): Initializes registry with generated binding
 * - WebServer retrieved from registry: Framework auto-registers the server
 * - No reflection or classpath scanning at runtime (GraalVM native-image ready)
 */
@Service.GenerateBinding
public class Main {

    static {
        LogConfig.initClass();
    }

    /**
     * Cannot be instantiated.
     */
    private Main() {
    }

    /**
     * Application main entry point.
     *
     * @param args command line arguments (not used)
     * @throws InterruptedException if the main thread is interrupted
     */
    public static void main(String[] args) throws InterruptedException {
        // Configure logging
        LogConfig.configureRuntime();

        // Start the service registry - uses generated ApplicationBinding to avoid reflection and runtime lookup
        // ApplicationBinding is generated by helidon-service-maven-plugin at build time
        // This provides faster startup and better GraalVM Native Image support
        ServiceRegistryManager manager = ServiceRegistryManager.start(ApplicationBinding.create());

        // Retrieve the WebServer instance from the service registry
        // WebServer is automatically registered by Helidon when using declarative endpoints
        WebServer server = manager.registry().get(WebServer.class);

        System.out.println("Student Service started on port: " + server.port());
        System.out.println("Health: http://localhost:" + server.port() + "/observe/health");

        // Keep JVM alive - DO NOT REMOVE
        Thread.currentThread().join();
    }

}
